datalakehouse:
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: postgres_user
      password: postgres_password
      port: 5432
      dbname: postgres_db
      schema: public
      threads: 3
      keepalives_idle: 0 # default 0, indicating the system default
  target: dev
