version: '3'
services:
  vertica:
    environment:
      APP_DB_USER: "newdbadmin"
      APP_DB_PASSWORD: "vertica"
      TZ: "Europe/Moscow"
    container_name: vertica-ce
    image: vertica/vertica-ce:latest
    ports:
      - "5433:5433"
      - "5444:5444"
    deploy:
      mode: global
    volumes:
      - type: volume
        source: vertica-data2
        target: /vertica-data2
volumes:
  vertica-data2: